[package]
name = "stable-trie"
version = "0.1.3"
description = "Stable-memory trie-based key-value map"
repository = "https://github.com/research-ag/stable-trie"
keywords = [ "set", "enumeration", "lookup", "bijective", "key-value" ]
license = "Apache-2.0"
files = [ "**/*.mo", "**/*.md", "**/*.toml" ]

[dependencies]
core = "2.5.0"

[dev-dependencies]
bench-helper = "0.0.3"
prng = "0.2.0"

[requirements]
moc = "1.0.0"

[toolchain]
moc = "1.9.0"
wasmtime = "44.0.1"
pocket-ic = "9.0.3"
