[package]
name = "stable-trie"
version = "0.0.1"
description = "Stable-memory trie-based key-value map"
repository = "https://github.com/research-ag/stable-trie"
keywords = [ "set", "enumeration", "lookup", "bijective" ]
license = "Apache-2.0"

[dependencies]
base = "0.14.13"

[dev-dependencies]
test = "2.1.1"
prng = "0.0.5"
bench = "1.0.0"

[toolchain]
moc = "0.14.13"
wasmtime = "34.0.1"
pocket-ic = "9.0.3"
