[package]
name = "stable-trie"
version = "0.0.5"
description = "Stable-memory trie-based key-value map"
repository = "https://github.com/research-ag/stable-trie"
keywords = [ "set", "enumeration", "lookup", "bijective", "key-value" ]
license = "Apache-2.0"

[dependencies]
core = "2.0.0"

[dev-dependencies]
bench = "2.0.1"
prng = "0.0.8"

[requirements]
moc = "1.0.0"

[toolchain]
moc = "1.1.0"
wasmtime = "40.0.0"
