[package]
name = "stable_trie_enumeration"
version = "0.0.1"
description = ""
repository = "https://github.com/research-ag/stable_trie_enumeration"
keywords = [ "stable", "trie", "enumeration" ]
license = "Apache-2.0"

[dependencies]
base = "0.11.1"

[dev-dependencies]
test = "2.0.0"
prng = "0.0.3"
bench = "1.0.0"

[toolchain]
moc = "0.11.1"
wasmtime = "20.0.2"
pocket-ic = "1.0.0"
