name: App build
on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review, unlabeled]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install mops
        uses: ZenVoich/setup-mops@v1.2.0

      - name: Show mops version
        run: |
          mops --version
          $(mops toolchain bin moc) --version

      - name: Make sure moc is installed
        run: mops toolchain bin moc || mops toolchain use moc latest

      - name: Make sure toolchain is installed
        run: mops install

      - name: Run tests
        run: mops test

      - name: run benches
        run: mops bench
